---
name: Build Docker Image

on:
  push:
    branches: [main]
    paths:
      - .github/workflows/build-docker-image.yml
      - .devcontainer/Dockerfile
      - uv.lock

  workflow_dispatch:

jobs:
  build-and-push:
    permissions:
      contents: read
      packages: write
      attestations: write

    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repo to depth of 2 so we can see what has changed (if needed).
        uses: actions/checkout@v4
        with:
          fetch-depth: 2
          submodules: false
          clean: true

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Docker login
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set short git commit SHA
        run: |
          calculatedSha=$(git rev-parse --short ${{ github.sha }})
          echo "COMMIT_SHORT_SHA=$calculatedSha" >> $GITHUB_ENV

      - name: Build and Push Production Docker Image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: .devcontainer/Dockerfile
          push: true
          tags: |
            ghcr.io/joejcollins/colonel-white:latest
            ghcr.io/joejcollins/colonel-white:${{ env.COMMIT_SHORT_SHA }}
          platforms: linux/amd64,linux/arm64
